package io.github.taetae98coding.jarvis.ui.unitconverter

import io.github.taetae98coding.jarvis.domain.unitconverter.MeasureUnit
import io.github.taetae98coding.jarvis.domain.unitconverter.UnitCategory

internal val UnitCategory.label: String
    get() = when (this) {
        UnitCategory.LENGTH -> "길이"
        UnitCategory.AREA -> "넓이"
        UnitCategory.MASS -> "무게"
        UnitCategory.VOLUME -> "부피"
        UnitCategory.TEMPERATURE -> "온도"
        UnitCategory.SPEED -> "속도"
        UnitCategory.DATA -> "데이터"
        UnitCategory.TIME -> "시간"
        UnitCategory.ENERGY -> "에너지"
    }

/** 값 뒤에 붙이는 기호. */
internal val MeasureUnit.symbol: String
    get() = when (this) {
        MeasureUnit.MILLIMETER -> "mm"
        MeasureUnit.CENTIMETER -> "cm"
        MeasureUnit.METER -> "m"
        MeasureUnit.KILOMETER -> "km"
        MeasureUnit.INCH -> "in"
        MeasureUnit.FOOT -> "ft"
        MeasureUnit.YARD -> "yd"
        MeasureUnit.MILE -> "mi"
        MeasureUnit.NAUTICAL_MILE -> "nmi"
        MeasureUnit.JA -> "자"
        MeasureUnit.SQUARE_CENTIMETER -> "cm²"
        MeasureUnit.SQUARE_METER -> "m²"
        MeasureUnit.PYEONG -> "평"
        MeasureUnit.HECTARE -> "ha"
        MeasureUnit.SQUARE_KILOMETER -> "km²"
        MeasureUnit.SQUARE_FOOT -> "ft²"
        MeasureUnit.SQUARE_YARD -> "yd²"
        MeasureUnit.ACRE -> "ac"
        MeasureUnit.SQUARE_MILE -> "mi²"
        MeasureUnit.MILLIGRAM -> "mg"
        MeasureUnit.GRAM -> "g"
        MeasureUnit.KILOGRAM -> "kg"
        MeasureUnit.TONNE -> "t"
        MeasureUnit.OUNCE -> "oz"
        MeasureUnit.POUND -> "lb"
        MeasureUnit.DON -> "돈"
        MeasureUnit.NYANG -> "냥"
        MeasureUnit.GEUN -> "근"
        MeasureUnit.MILLILITER -> "mL"
        MeasureUnit.LITER -> "L"
        MeasureUnit.CUBIC_METER -> "m³"
        MeasureUnit.US_TEASPOON -> "tsp"
        MeasureUnit.US_TABLESPOON -> "tbsp"
        MeasureUnit.US_FLUID_OUNCE -> "fl oz"
        MeasureUnit.US_CUP -> "cup"
        MeasureUnit.US_GALLON -> "gal"
        MeasureUnit.DOE -> "되"
        MeasureUnit.CELSIUS -> "°C"
        MeasureUnit.FAHRENHEIT -> "°F"
        MeasureUnit.KELVIN -> "K"
        MeasureUnit.METER_PER_SECOND -> "m/s"
        MeasureUnit.KILOMETER_PER_HOUR -> "km/h"
        MeasureUnit.MILE_PER_HOUR -> "mph"
        MeasureUnit.KNOT -> "kn"
        MeasureUnit.BIT -> "bit"
        MeasureUnit.BYTE -> "B"
        MeasureUnit.KILOBYTE -> "KB"
        MeasureUnit.MEGABYTE -> "MB"
        MeasureUnit.GIGABYTE -> "GB"
        MeasureUnit.TERABYTE -> "TB"
        MeasureUnit.KIBIBYTE -> "KiB"
        MeasureUnit.MEBIBYTE -> "MiB"
        MeasureUnit.GIBIBYTE -> "GiB"
        MeasureUnit.TEBIBYTE -> "TiB"
        MeasureUnit.MILLISECOND -> "ms"
        MeasureUnit.SECOND -> "s"
        MeasureUnit.MINUTE -> "min"
        MeasureUnit.HOUR -> "h"
        MeasureUnit.DAY -> "일"
        MeasureUnit.WEEK -> "주"
        MeasureUnit.JOULE -> "J"
        MeasureUnit.KILOJOULE -> "kJ"
        MeasureUnit.CALORIE -> "cal"
        MeasureUnit.KILOCALORIE -> "kcal"
        MeasureUnit.WATT_HOUR -> "Wh"
        MeasureUnit.KILOWATT_HOUR -> "kWh"
    }

/** 목록과 메뉴에 보이는 이름. 10진·2진 접두어와 미국 관습 단위는 이름에서 구별한다. */
internal val MeasureUnit.label: String
    get() = when (this) {
        MeasureUnit.MILLIMETER -> "밀리미터"
        MeasureUnit.CENTIMETER -> "센티미터"
        MeasureUnit.METER -> "미터"
        MeasureUnit.KILOMETER -> "킬로미터"
        MeasureUnit.INCH -> "인치"
        MeasureUnit.FOOT -> "피트"
        MeasureUnit.YARD -> "야드"
        MeasureUnit.MILE -> "마일"
        MeasureUnit.NAUTICAL_MILE -> "해리"
        MeasureUnit.JA -> "자(尺)"
        MeasureUnit.SQUARE_CENTIMETER -> "제곱센티미터"
        MeasureUnit.SQUARE_METER -> "제곱미터"
        MeasureUnit.PYEONG -> "평"
        MeasureUnit.HECTARE -> "헥타르"
        MeasureUnit.SQUARE_KILOMETER -> "제곱킬로미터"
        MeasureUnit.SQUARE_FOOT -> "제곱피트"
        MeasureUnit.SQUARE_YARD -> "제곱야드"
        MeasureUnit.ACRE -> "에이커"
        MeasureUnit.SQUARE_MILE -> "제곱마일"
        MeasureUnit.MILLIGRAM -> "밀리그램"
        MeasureUnit.GRAM -> "그램"
        MeasureUnit.KILOGRAM -> "킬로그램"
        MeasureUnit.TONNE -> "톤"
        MeasureUnit.OUNCE -> "온스"
        MeasureUnit.POUND -> "파운드"
        MeasureUnit.DON -> "돈"
        MeasureUnit.NYANG -> "냥"
        MeasureUnit.GEUN -> "근(600 g)"
        MeasureUnit.MILLILITER -> "밀리리터"
        MeasureUnit.LITER -> "리터"
        MeasureUnit.CUBIC_METER -> "세제곱미터"
        MeasureUnit.US_TEASPOON -> "티스푼(US)"
        MeasureUnit.US_TABLESPOON -> "테이블스푼(US)"
        MeasureUnit.US_FLUID_OUNCE -> "액량 온스(US)"
        MeasureUnit.US_CUP -> "컵(US)"
        MeasureUnit.US_GALLON -> "갤런(US)"
        MeasureUnit.DOE -> "되"
        MeasureUnit.CELSIUS -> "섭씨"
        MeasureUnit.FAHRENHEIT -> "화씨"
        MeasureUnit.KELVIN -> "켈빈"
        MeasureUnit.METER_PER_SECOND -> "초속(미터)"
        MeasureUnit.KILOMETER_PER_HOUR -> "시속(킬로미터)"
        MeasureUnit.MILE_PER_HOUR -> "시속(마일)"
        MeasureUnit.KNOT -> "노트"
        MeasureUnit.BIT -> "비트"
        MeasureUnit.BYTE -> "바이트"
        MeasureUnit.KILOBYTE -> "킬로바이트(10³)"
        MeasureUnit.MEGABYTE -> "메가바이트(10⁶)"
        MeasureUnit.GIGABYTE -> "기가바이트(10⁹)"
        MeasureUnit.TERABYTE -> "테라바이트(10¹²)"
        MeasureUnit.KIBIBYTE -> "키비바이트(2¹⁰)"
        MeasureUnit.MEBIBYTE -> "메비바이트(2²⁰)"
        MeasureUnit.GIBIBYTE -> "기비바이트(2³⁰)"
        MeasureUnit.TEBIBYTE -> "테비바이트(2⁴⁰)"
        MeasureUnit.MILLISECOND -> "밀리초"
        MeasureUnit.SECOND -> "초"
        MeasureUnit.MINUTE -> "분"
        MeasureUnit.HOUR -> "시간"
        MeasureUnit.DAY -> "일"
        MeasureUnit.WEEK -> "주"
        MeasureUnit.JOULE -> "줄"
        MeasureUnit.KILOJOULE -> "킬로줄"
        MeasureUnit.CALORIE -> "칼로리"
        MeasureUnit.KILOCALORIE -> "킬로칼로리"
        MeasureUnit.WATT_HOUR -> "와트시"
        MeasureUnit.KILOWATT_HOUR -> "킬로와트시"
    }

/** 기호와 이름이 같으면(평, 돈, 되 …) 한 번만 쓴다. */
internal val MeasureUnit.menuLabel: String
    get() = if (label == symbol) label else "$label ($symbol)"

internal fun amountText(value: String, unit: MeasureUnit): String = "$value ${unit.symbol}"
